export const SET_LOCALE = 'SET_LOCALE';
export const FETCH_GAMES_STARTED = 'FETCH_GAMES_STARTED';
export const FETCH_GAMES_SUCCEEDED = 'FETCH_GAMES_SUCCEEDED';
export const FETCH_GAMES_FAILED = 'FETCH_GAMES_FAILED';
export const SET_GAMES_SEARCH_FILTERS = 'SET_GAMES_SEARCH_FILTERS';
export const CLEAR_GAMES_STATE = 'CLEAR_GAMES_STATE';