export default {
    "header.closeMenu": "Close menu",
    "header.openMenu": "Open menu",
    "header.home": "Home",
    "header.search": "Search",
    "header.about": "About",
    "footer.about": "About this site",
    "footer.copyright": "Copyright © Barry McCormack 2020",
    "homePage.title": "New and upcoming games",
    "searchPage.title": "Games search",
    "searchPage.searchLabel": "Search for a game",
    "aboutPage.aboutText": "About text",
    "errorPage.errorHeading": "404 - Page Not Found",
    "errorPage.errorMessage": "Click {link} to go back to the homepage",
    "gameslist.error": "Error: Could not retrieve games",
    "game.error": "Error: Could not retrieve game",
    "gameHeader.posterAlt": "Game artwork poster",
    "gameHeader.viewOnSite": "View on GiantBomb",
    "gameHeader.aliases": "Also known as: ",
    "gameHeader.released": "Released: {date}",
    "gameFooter.poweredBy": "Powered by {link}",
    "gameDetails.franchises": "Franchises: ",
    "gameDetails.genres": "Genres: ",
    "gameDetails.publishers": "Publishers: ",
    "gameDetails.developers": "Developers: ",
    "gameDetails.themes": "Themes: ",
    "gameDetails.platforms": "Platforms: ",
};