export default {
    "header.closeMenu": "Close Menu",
    "header.openMenu": "Open Menu",
    "header.home": "Home",
    "header.about": "About",
    "footer.about": "About This Site",
    "footer.copyright": "Copyright © Barry McCormack 2020",
    "aboutPage.aboutText": "About Text",
    "errorPage.errorHeading": "404 - Page Not Found",
    "errorPage.errorMessage": "Click {link} to go back to the homepage",
    "searchPage.searchLabel": "Search For Game",
    "homePage.gamesTitle": "Games",
    "gameslist.error": "Error: Could not retrieve games",
    "game.error": "Error: Could retrieve game",
    "gameHeader.viewOnSite": "View on GiantBomb",
    "gameHeader.aliases": "Also Known as: ",
    "gameHeader.released": "Released: {date}",
    "gameFooter.poweredBy": "Powered By {link}",
};