export default {
    "header.closeMenu": "FR Close Menu",
    "header.openMenu": "FR Open Menu",
    "header.home": "FR Home",
    "header.about": "FR About",
    "footer.about": "FR About This Site",
    "footer.copyright": "FR Copyright © Barry McCormack 2020",
    "aboutPage.aboutText": "FR About Text",
    "errorPage.errorHeading": "FR 404 - Page Not Found",
    "errorPage.errorMessage": "FR Click {link} to go back to the homepage",
    "searchPage.searchLabel": "FR Search For Game",
    "homePage.gamesTitle": "FR Games",
    "gameslist.error": "FR Error: Could not retrieve games",
    "game.error": "FR Error: Could retrieve game",
    "gameHeader.viewOnSite": "FR View on GiantBomb",
    "gameHeader.aliases": "FR Also Known as: ",
    "gameHeader.released": "FR Released: {date}",
    "gameFooter.poweredBy": "FR Powered By {link}",
    "gameDetails.franchises": "FR Franchises: ",
    "gameDetails.genres": "FR Genres: ",
    "gameDetails.publishers": "FR Publishers: ",
    "gameDetails.developers": "FR Developers: ",
    "gameDetails.themes": "FR Themes: ",
    "gameDetails.platforms": "FR Platforms: ",
};